version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'

    - package-ecosystem: 'npm'
      versioning-strategy: 'lockfile-only'
      directory: '/'
      schedule:
          interval: 'daily'
      # Setting this to 0 disables regular version updates but allows security updates to inherit the settings below.
      open-pull-requests-limit: 0
      labels:
          - 'dependencies'
      groups:
          angular:
              applies-to: 'security-updates'
              patterns:
                  - '@angular*'
          eslint:
              applies-to: 'security-updates'
              patterns:
                  - '@eslint/*'
                  - 'eslint*'
          markdownlint:
              applies-to: 'security-updates'
              patterns:
                  - 'markdownlint*'
          prettier:
              applies-to: 'security-updates'
              patterns:
                  - 'prettier*'
          stylelint:
              applies-to: 'security-updates'
              patterns:
                  - 'stylelint*'
          vitest:
              applies-to: 'security-updates'
              patterns:
                  - '@vitest/*'
                  - 'vite'
                  - 'vitest'
          remaining-security-updates:
              applies-to: 'security-updates'
              patterns:
                  - '*'
