packages:
  - '!dist/**/*'
blockExoticSubdeps: true
ignoreDepScripts: true
managePackageManagerVersions: false
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@dnd-mapp/*'
packageManagerStrictVersion: true
savePrefix: '~'
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 2880
verifyDepsBeforeRun: prompt
