packages:
  - projects/*
blockExoticSubdeps: true
ignoreDepScripts: true
ignoreScripts: true
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@dnd-mapp/*'
nodeVersion: 24.14.0
savePrefix: '~'
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 2880
verifyDepsBeforeRun: prompt
