name: CI
description: Runs Continuous Integration checks
runs:
    using: composite
    steps:
        - name: Set up tools
          uses: ./.github/actions/setup-tools

        - name: Check formatting
          shell: bash
          run: pnpm format:check

        - name: Run linting
          shell: bash
          run: |
              pnpm lint
              pnpm stylelint

        - name: Compile library
          shell: bash
          run: pnpm build

        - name: Compile storybook
          shell: bash
          run: pnpm storybook:build
