name: Setup tools
description: Set up Node.js, Pnpm, and optionally install dependencies
inputs:
    install-dependencies:
        required: false
        description: Should dependencies be installed
        default: 'true'
runs:
    using: composite
    steps:
        - name: Set up Pnpm
          uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

        - name: Set up Node.js
          uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
          with:
              node-version-file: '.tool-versions'
              cache-dependency-path: 'pnpm-lock.yaml'
              cache: 'pnpm'
              registry-url: 'https://registry.npmjs.org'

        - name: Install dependencies
          if: ${{ inputs.install-dependencies == 'true' }}
          shell: bash
          run: pnpm install --frozen-lockfile
